base:
 aws: False
 aws_url: ""
 local: "/home/timmytime/IdeaProjects/predictor-ml-model/res/"
 docker_host: "http://localhost"
 train_path: "train/<type>/<key>/"
 vocab_path: "vocab/<type>/<key>/"
 country_results_train_history_file: "country-matches-train-history.json"
 country_scores_train_history_file: "country-scores-train-history.json"
 players_goals_train_history_file: "players-goals-train-history.json"
 players_first_goal_train_history_file: "players-first-goal-train-history.json"
 players_last_goal_train_history_file: "players-last-goal-train-history.json"

learning:

 default:
         batch_size: 100
         steps: 1000
         months_per_cycle: 4
         start_day: 1
         start_month: 1
         start_year: 2012
         end_day: 14
         end_month: 7
         end_year: 2018
         hash_bins: 25000
         hidden_units: [10, 20, 10]
         aws_debug: False
         historic: True

 england:
         start_day: 1
         start_month: 1
         start_year: 2012
         end_day: 14
         end_month: 8
         end_year: 2018
         hash_bins: 25000
         hidden_units: [10, 20, 10]
         aws_debug: True

 player:
           batch_size: 100
           steps: 1000
           months_per_cycle: 4
           start_day: 1
           start_month: 1
           start_year: 2012
           end_day: 14
           end_month: 7
           end_year: 2018
           hash_bins: 25000
           hidden_units: [10, 20, 10]
           aws_debug: False
           historic: True


vocab:
 team_vocab_url: ":8090/api/prediction/teams"
 player_by_country_vocab_url: ":8090/api/prediction/players/by-country-dict"
 player_vocab_url: ":8090/api/prediction/players/by-player-dict"

analysis: 
 player_model_url: ":8090/api/prediction/ml-data/players/player/"
 team_model_url: ":8090/api/prediction/ml-data/competition/"
 types_url: ":8090/api/prediction/cache/types"
 countries_url: ":8090/api/prediction/cache/countries"
 players_by_team_url: ":8090/api/prediction/teams/<team>/players"
 comps_by_country_url: ":8090/api/prediction/cache/competition-count"

receipt:
 train_receipt_url: ":8090/api/prediction/ml-data/train/receipt"
 predict_receipt_url: ":8090/api/prediction/ml-data/predict/receipt"

auth:
 username: ""
 password: ""
 url: "http://ec2-54-85-206-187.compute-1.amazonaws.com:8091/api/prediction/authenticate"
