base:
 aws: False
 aws_url: ""
 local: "/home/timmytime/IdeaProjects/predictor-ml-model/res/"
 docker_host: "http://localhost"

vocab:
 team_vocab_url: ":8090/api/prediction/teams"
 player_by_country_vocab_url: ":8090/api/prediction/players/by-country-dict"
 player_vocab_url: ":8090/api/prediction/players/by-player-dict"
 team_vocab_file: "/home/timmytime/IdeaProjects/predictor-ml-model/res/team-vocab"
 player_vocab_file: "/home/timmytime/IdeaProjects/predictor-ml-model/res/player-vocab"
 player_by_country_vocab_file: "/home/timmytime/IdeaProjects/predictor-ml-model/res/player-by-country-vocab"

analysis: 
 player_model_url: ":8090/api/prediction/ml-data/players/player/"
 team_model_url: ":8090/api/prediction/ml-data/competition/"
 types_url: ":8090/api/prediction/cache/types"
 countries_url: ":8090/api/prediction/cache/countries"
 players_by_team_url: ":8090/api/prediction/teams/<team>/players"
 comps_by_country_url: ":8090/api/prediction/cache/competition-count"
 historic: True

receipt:
 train_receipt_url: ":8090/api/prediction/ml-data/train/receipt"
 predict_receipt_url: ":8090/api/prediction/ml-data/predict/receipt"

auth:
 username: ""
 password: ""
 url: "http://ec2-54-85-206-187.compute-1.amazonaws.com:8091/api/prediction/authenticate"
